version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - SQLITE_DB_PATH=./database
      - PORT=3001
    volumes:
      - ./backend/database:/database
      - ./backend:/backend
      - /backend/node_modules
